CREATE DATABASE IF NOT EXISTS soa;
USE soa;

CREATE TABLE IF NOT EXISTS autores (
    AUT_ID INT AUTO_INCREMENT PRIMARY KEY,
    AUT_NOM VARCHAR(100) NOT NULL,
    AUT_CORREO VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS libros (
    LIB_ID INT AUTO_INCREMENT PRIMARY KEY,
    LIB_TITULO VARCHAR(150) NOT NULL,
    LIB_ANIO INT NOT NULL,
    AUT_ID INT NOT NULL,
    FOREIGN KEY (AUT_ID) REFERENCES autores(AUT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
